version: '3.8'
services:
  
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio_data:/data # Lưu dữ liệu tại thư mục minio_data cùng cấp
    command: server /data --console-address ":9001"
    restart: always


  # Thêm service mới này vào:
  vip-worker:
    build:
      context: .
      dockerfile: Comax.VipWorker/Dockerfile
    container_name: comax-vip-worker
    restart: always
    # Cấu hình kết nối DB y hệt như bên API
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=ComaxDb;User=root;Password=11111111;
    depends_on:
      - db # Đợi DB chạy xong thì Worker mới ch
  redis: 
    image: redis:alpine
    container_name: comax_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - comax-network

volumes:
  redis_data:
    driver: local